"""Create the initial user and role schema.

Revision ID: 0001_users
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001_users"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

role_enum = postgresql.ENUM(
    "ORGANIZER",
    "CUSTOMER",
    "GATE",
    name="role_enum",
    create_type=False,
)


def upgrade() -> None:
    # UUIDv7 values and credential hashes are generated by the application, so
    # the initial schema does not require optional PostgreSQL extensions.
    role_enum.create(op.get_bind(), checkfirst=True)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", role_enum, nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default=sa.true(),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) BETWEEN 1 AND 120",
            name=op.f("ck_users_display_name_length"),
        ),
        sa.CheckConstraint(
            "email = lower(btrim(email))",
            name=op.f("ck_users_email_normalized"),
        ),
        sa.CheckConstraint(
            "length(email) BETWEEN 3 AND 320",
            name=op.f("ck_users_email_length"),
        ),
        sa.CheckConstraint(
            "length(password_hash) > 0",
            name=op.f("ck_users_password_hash_not_empty"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_role_is_active", "users", ["role", "is_active"])


def downgrade() -> None:
    op.drop_index("ix_users_role_is_active", table_name="users")
    op.drop_table("users")
    role_enum.drop(op.get_bind(), checkfirst=True)
